In [1]:
import numpy as np

In [2]:
numbers = np.array([2,3,5,7,11])

In [4]:
type(numbers)

numpy.ndarray

In [7]:
numbers = np.array([1,2,3,22])

In [8]:
numbers

array([ 1,  2,  3, 22])

In [10]:
numbers = np.array([[1,2,3],[4,5,6]])
numbers

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
import numpy as np

np.array( [x for x in range(2,21,2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [1]:
def greeting():
    name = input('Enter Your name')
    print(f'Welcome {name}')

In [4]:
greeting??

Signature: greeting()
Docstring: <no docstring>
Source:   
def greeting():
    name = input('Enter Your name')
    print(f'Welcome {name}')
File:      c:\users\moham\appdata\local\temp\ipykernel_25872\1542952077.py
Type:      function

In [5]:
def average(*args):
    return sum(args) / len(args)

average(1,2,3,4,5)

3.0

In [6]:
x = 10

In [7]:
def global_var():
    global x;
    x = 'Hello'
    print('x printed from modify',x)

global_var()

x printed from modify Hello


In [8]:
x

'Hello'

In [10]:
f= lambda x: x **2
f(2)

4

In [11]:
def myfunc(n):
    return lambda a:a *n

mydoubler = myfunc(2)
print(mydoubler(11))

22


In [12]:
def quadratic(a,b,c):
    return lambda x: a * (x ** 2) + b * x - c

quadratic(2,3,5)(2)

9

In [1]:
import numpy as np

In [4]:
np.array([2,5,7,9])

array([2, 5, 7, 9])

In [5]:
np.array([2.5,5,7,9.2])

array([2.5, 5. , 7. , 9.2])

In [7]:
import numpy as np

In [9]:
newarray = np.array([1,2,3,4,5])

In [11]:
type(newarray)

numpy.ndarray

In [12]:
np.array([1,2,3,4,5] , dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [13]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.ones((4,10,3) , dtype=int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [18]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [19]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.random.random((3,3))

array([[0.84384343, 0.0455073 , 0.44100848],
       [0.7598793 , 0.12064538, 0.78389245],
       [0.8833467 , 0.87781724, 0.0693377 ]])

In [23]:
np.random.normal(0,1,(3,3))

array([[ 0.18389161, -0.98470463, -0.87429366],
       [-0.79200954,  0.91050661, -0.18944819],
       [ 2.13720964, -0.56468018, -0.69638742]])

In [24]:
np.random.randint(50,100,(3,3))

array([[89, 96, 71],
       [51, 71, 55],
       [81, 86, 51]])

In [25]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.empty((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
x = np.zeros((3,4,5),dtype='int64')

In [31]:
x

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [36]:
print("x ndim:", x.ndim)
print('x shape:', x.shape)
print('x size: ', x.size)

x ndim: 3
x shape: (3, 4, 5)
x size:  60


In [37]:
print('dtype' , x.dtype)

dtype int64


In [39]:
x1= np.array([5,0,3,3,7,9])
x1

array([5, 0, 3, 3, 7, 9])

In [41]:
x1[3]

3

In [43]:
x2 = np.array([[3,5,2,4],[7,6,8,8],[1,6,7,7]])
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [44]:
x2[1,1]

6

In [45]:
x2[0,0] = 5

In [46]:
x2

array([[5, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [48]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
x[1:5]

array([1, 2, 3, 4])

In [54]:
x = np.random.randint(2,20,10)
x

array([ 8,  3,  9, 19,  6, 13,  3,  5, 12,  3])

In [55]:
x[2:6]

array([ 9, 19,  6, 13])

In [56]:
x[:6]

array([ 8,  3,  9, 19,  6, 13])

In [57]:
x[6:]

array([ 3,  5, 12,  3])

In [58]:
x[::2]

array([ 8,  9,  6,  3, 12])

In [59]:
x[1::2]

array([ 3, 19, 13,  5,  3])

In [60]:
x[::-1]

array([ 3, 12,  5,  3, 13,  6, 19,  9,  3,  8])

In [61]:
x

array([ 8,  3,  9, 19,  6, 13,  3,  5, 12,  3])

In [62]:
x[5::-1]

array([13,  6, 19,  9,  3,  8])

In [63]:
x2 = np.array([[12,5,2,4],[7,6,8,8],[1,6,7,7]])
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [72]:
x2[0:2,2:3]

array([[2],
       [8]])

In [69]:
x2[1,1:3]

array([6, 8])

In [73]:
x2[:2,:3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [74]:
x2[:3,::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [75]:
x2[1:,3:]

array([[8],
       [7]])

In [76]:
x2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [77]:
x2[:2,::-1]

array([[ 4,  2,  5, 12],
       [ 8,  8,  6,  7]])

In [ ]:
x2 = np.array([[12,5,2,4],[7,6,8,8],[1,6,7,7]])
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [78]:
x2[:,0]

array([12,  7,  1])

In [79]:
x2[0]

array([12,  5,  2,  4])

In [81]:
x2 = np.array([[12,5,2,4],[7,6,8,8],[1,6,7,7]])
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [86]:
x2_sub = x2[:2,:2]

In [87]:
x2_sub

array([[12,  5],
       [ 7,  6]])

In [88]:
grid = np.arange(1,10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
grid = grid.reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
grid.shape

(3, 3)