In [1]:
import numpy as np

In [9]:
numbers = np.array([2,3,5,7,11])

In [3]:
type(numbers)

numpy.ndarray

In [10]:
numbers

array([ 2,  3,  5,  7, 11])

#### Multidimensional Arguments

In [11]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.array([x for x in range(2,21,2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [21]:
np.array([[x for x in range(2,11,2)] , [x for x in range(1,10) if x % 2 != 0]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [23]:
import numpy as np
integers = np.array([[1,2,3] , [4,5,6]])
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
floats = np.array([0.0,0.1,0.2,0.3,0.4])

In [26]:
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

In [27]:
integers.dtype

dtype('int32')

In [52]:
integers.ndim

2

In [28]:
floats.dtype

dtype('float64')

In [29]:
integers.ndim

2

In [30]:
floats.ndim

1

In [31]:
integers.shape

(2, 3)

In [32]:
floats.shape

(5,)

In [34]:
integers.size

6

In [36]:
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
integers.itemsize

4

In [37]:
floats.size

5

In [38]:
floats.itemsize

8

In [39]:
floats.dtype

dtype('float64')

In [42]:
for row in integers:
    for column in row:
        print(column,end=" ")
    print()

1 2 3 
4 5 6 


In [43]:
for i in integers.flat:
    print(i, end=' ')

1 2 3 4 5 6 

In [47]:
a = np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])
a

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [45]:
a.ndim

2

In [46]:
a.shape

(2, 5)

In [48]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [49]:
np.ones((2,4) , dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [50]:
np.full((3,5),13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [51]:
np.full((4,4),28)

array([[28, 28, 28, 28],
       [28, 28, 28, 28],
       [28, 28, 28, 28],
       [28, 28, 28, 28]])

In [54]:
np.full((4,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [63]:
np.linspace(0.0,1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [64]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [66]:
np.arange(1,37).reshape(6,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [67]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [68]:
np.arange(1,100001).reshape(4,25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [69]:
np.arange(1,100001).reshape(100,1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

In [71]:
np.arange(2,41,2).reshape(4,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [2]:
import random

%timeit rolls_list = \
    [random.randrange(1,7) for i in range(0,6000000)]

2.51 s ± 148 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [1]:
import numpy as np
%timeit rolls_array = np.random.randint(1,7,6000000)

62.7 ms ± 1.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [75]:
%timeit rolls_array = np.random.randint(1,7,600000000)

6.11 s ± 386 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [76]:
%timeit -n3 -r2 rolls_array = np.random.randint(1,7,6000000)

63.2 ms ± 4.55 ms per loop (mean ± std. dev. of 2 runs, 3 loops each)


In [77]:
%save

UsageError: Missing filename.


In [78]:
%%stata

UsageError: Cell magic `%%stata` not found.


In [79]:
%timeit sum([x for x in range(10000000)])

875 ms ± 26.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [82]:
%timeit np.arange(1000000000).sum()

2.35 s ± 27.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Array Operator

In [83]:
numbers = np.arange(1,6)
numbers

array([1, 2, 3, 4, 5])

In [84]:
numbers * 2

array([ 2,  4,  6,  8, 10])

In [85]:
numbers **3

array([  1,   8,  27,  64, 125], dtype=int32)

In [86]:
numbers

array([1, 2, 3, 4, 5])

In [87]:
numbers += 10

In [88]:
numbers

array([11, 12, 13, 14, 15])

In [89]:
numbers

array([11, 12, 13, 14, 15])

In [90]:
numbers2 = np.linspace(1.1,5.5,5)

In [91]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [93]:
numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

In [94]:
numbers

array([11, 12, 13, 14, 15])

In [95]:
numbers >= 13

array([False, False,  True,  True,  True])

In [96]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [97]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [98]:
numbers == numbers2

array([False, False, False, False, False])

In [99]:
numbers == numbers

array([ True,  True,  True,  True,  True])

In [100]:
np.arange(1,6) ** 2

array([ 1,  4,  9, 16, 25])

: 

In [2]:
import numpy as np

grades = np.array([[87,96,70] , [100,87,90] , [94,77,90] , [100,81,82]])
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [4]:
grades.sum()

1054

In [5]:
grades.min()

70

In [6]:
grades.max()

100

In [7]:
grades.mean()

87.83333333333333

In [8]:
grades.std()

8.792357792739987

In [9]:
grades.var()

77.30555555555556

In [15]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

In [19]:
import numpy as np

grades = np.random.randint(60,101,12).reshape(3,4)
grades

array([[99, 99, 85, 66],
       [61, 91, 83, 65],
       [90, 88, 99, 78]])

In [21]:
grades.mean()

83.66666666666667

In [24]:
# avg for each column
grades.mean(axis=0)

array([83.33333333, 92.66666667, 89.        , 69.66666667])

In [25]:
# avg for each row

grades.mean(axis=1)

array([87.25, 75.  , 88.75])

In [26]:
import numpy as np

numbers = np.array([1,4,9,16,25,36])

np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [28]:
numbers2 = np.arange(1,7) * 10
numbers2

array([10, 20, 30, 40, 50, 60])

In [29]:
np.add(numbers , numbers2)

array([11, 24, 39, 56, 75, 96])

In [30]:
numbers2 + numbers

array([11, 24, 39, 56, 75, 96])

In [32]:
numbers2

array([10, 20, 30, 40, 50, 60])

In [31]:
np.multiply(numbers2,5)

array([ 50, 100, 150, 200, 250, 300])

In [34]:
numbers2 * 2

array([ 20,  40,  60,  80, 100, 120])

In [36]:
numbers3 = numbers2.reshape(2,3)
numbers3

array([[10, 20, 30],
       [40, 50, 60]])

In [37]:
numbers4 = np.array([2,4,6])

In [38]:
np.multiply(numbers3,numbers4)

array([[ 20,  80, 180],
       [ 80, 200, 360]])

In [40]:
numbers = np.arange(1,6)

np.power(numbers,3)

array([  1,   8,  27,  64, 125], dtype=int32)

### 7.10 Indexing and Slicing

In [41]:
import numpy as np

grades = np.array([[87,96,70],[100,87,90],[94,77,90],[100,81,82]])

grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [45]:
grades[0,1]

96

In [46]:
grades[1]

array([100,  87,  90])

In [47]:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

In [48]:
grades[[1,3]]

array([[100,  87,  90],
       [100,  81,  82]])

In [50]:
grades[[0,2]]

array([[87, 96, 70],
       [94, 77, 90]])

In [53]:
grades[:,0]

array([ 87, 100,  94, 100])

In [54]:
grades[:,1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [65]:
grades[:,[0,2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

In [67]:
# Self Check

number = np.array([[1, 2, 3, 4, 5] , [ 6, 7, 8, 9, 10],[11, 12, 13, 14, 15]])
number

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [70]:
#Select the second row
number[1]

array([ 6,  7,  8,  9, 10])

In [75]:
# Select the first and third

number[[0,2]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [77]:
#Select the middle three columns.
number[:,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [78]:
import numpy as np

numbers = np.arange(1,6)

numbers

array([1, 2, 3, 4, 5])

In [79]:
numbers2 = numbers.view()
numbers2

array([1, 2, 3, 4, 5])

In [80]:
id(numbers)

2980482973392

In [81]:
id(numbers2)

2980482972432

In [86]:
numbers[1] *=10

In [87]:
numbers

array([ 1, 20,  3,  4,  5])

In [88]:
numbers2

array([ 1, 20,  3,  4,  5])

In [89]:
numbers2[1]  /= 10

In [90]:
numbers2

array([1, 2, 3, 4, 5])

In [91]:
numbers

array([1, 2, 3, 4, 5])

In [92]:
numbers2 = numbers[0:3]

In [93]:
numbers2

array([1, 2, 3])

In [94]:
id(numbers)

2980482973392

In [95]:
id(numbers2)

2980482970992

In [96]:
numbers[1] *= 20

In [97]:
numbers

array([ 1, 40,  3,  4,  5])

In [98]:
numbers2

array([ 1, 40,  3])

In [99]:
import numpy as np

numbers = np.arange(1,6)

numbers

array([1, 2, 3, 4, 5])

In [100]:
numbers2 = numbers.copy()

In [101]:
numbers2

array([1, 2, 3, 4, 5])

In [102]:
numbers[1] *= 10

In [103]:
numbers2

array([1, 2, 3, 4, 5])

In [104]:
numbers

array([ 1, 20,  3,  4,  5])

In [105]:
import numpy as np

In [106]:
grades = np.array([[87,96,70] , [100,87,90]])
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [107]:
grades.reshape(1,6)

array([[ 87,  96,  70, 100,  87,  90]])

In [108]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [109]:
grades.resize(1,6)

In [110]:
grades

array([[ 87,  96,  70, 100,  87,  90]])

In [111]:
grades

array([[ 87,  96,  70, 100,  87,  90]])

In [112]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [113]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [122]:
flattened = grades.flatten()
flattened

array([ 87,  96,  70, 100,  87,  90])

In [115]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [116]:
flattened

array([ 87,  96,  70, 100,  87,  90])

In [117]:
flattened[0] = 100
flattened

array([100,  96,  70, 100,  87,  90])

In [118]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [119]:
raveled = grades.ravel()

In [120]:
raveled

array([ 87,  96,  70, 100,  87,  90])

In [123]:
flattened

array([ 87,  96,  70, 100,  87,  90])

In [124]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [127]:
grades2 = np.array([[94, 77, 90], [100, 81, 82]])
grades2

array([[ 94,  77,  90],
       [100,  81,  82]])

In [128]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [129]:
import pandas as pd

In [130]:
grades = pd.Series([87,100,94])
grades

0     87
1    100
2     94
dtype: int64

In [131]:
pd.Series(98.6,range(3))

0    98.6
1    98.6
2    98.6
dtype: float64

In [132]:
pd.Series(17,range(4))

0    17
1    17
2    17
3    17
dtype: int64

In [133]:
pd.Series(3,range(4))

0    3
1    3
2    3
3    3
dtype: int64

In [134]:
pd.Series(9,range(2))

0    9
1    9
dtype: int64

In [135]:
grades[0]

87

In [136]:
grades.count()

3

In [137]:
grades.mean()

93.66666666666667

In [138]:
grades.min()

87

In [139]:
grades.max()

100

In [140]:
grades.std()

6.506407098647712

In [141]:
grades.describe()

count      3.000000
mean      93.666667
std        6.506407
min       87.000000
25%       90.500000
50%       94.000000
75%       97.000000
max      100.000000
dtype: float64

In [142]:
grades = pd.Series([87,100,94] , index=['Wally','Eva','Sam'])

In [143]:
grades

Wally     87
Eva      100
Sam       94
dtype: int64

In [144]:
pd.Series([10,20,30] , index=['Younis','Marina','Dina'])

Younis    10
Marina    20
Dina      30
dtype: int64

In [145]:
pd.Series([1,2,3] , index=['Gally','Shymaa','Salma'])

Gally     1
Shymaa    2
Salma     3
dtype: int64

In [146]:
pd.Series({'Wally' : 87 , 'Marina' : 90 , 'Younis' : 100})

Wally      87
Marina     90
Younis    100
dtype: int64

In [147]:
grades['Eva']

100

In [148]:
grades.Eva

100

In [151]:
grades.Wally

87

In [152]:
grades.dtype

dtype('int64')

In [153]:
grades.values

array([ 87, 100,  94], dtype=int64)

In [154]:
hardware = pd.Series(['Hammer' , 'Saw' , 'Wrnech'])
hardware

0    Hammer
1       Saw
2    Wrnech
dtype: object

In [155]:
hardware.str.contains('a')

0     True
1     True
2    False
dtype: bool

In [156]:
hardware.str.upper()

0    HAMMER
1       SAW
2    WRNECH
dtype: object

In [157]:
import numpy as np
import pandas as pd

In [158]:
temps = np.random.randint(60,101,6)
temps

array([63, 76, 68, 90, 94, 83])

In [159]:
temperatures = pd.Series(temps)
temperatures

0    63
1    76
2    68
3    90
4    94
5    83
dtype: int32

In [161]:
temperatures.min()

63

In [162]:
temperatures.max()

94

In [163]:
temperatures.mean()

79.0

In [160]:
temperatures.describe()

count     6.000000
mean     79.000000
std      12.231108
min      63.000000
25%      70.000000
50%      79.500000
75%      88.250000
max      94.000000
dtype: float64

In [164]:
import pandas as pd

In [165]:
grades_dict = {'Wally' : [87,96,70],
               'Eva' : [100,87,90],
               'Sam' : [94,77,90],
               'Katie' : [100,81,82],
               'Bob' : [83,65,85]
               }


In [166]:
grades = pd.DataFrame(grades_dict)

In [167]:
grades

Wally  Eva  Sam  Katie  Bob
0     87  100   94    100   83
1     96   87   77     81   65
2     70   90   90     82   85

In [170]:
grades.index = ['Test1' , 'Test2','Test3']


In [169]:
grades

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [171]:
grades['Eva']

Test1    100
Test2     87
Test3     90
Name: Eva, dtype: int64

In [172]:
grades.Eva

Test1    100
Test2     87
Test3     90
Name: Eva, dtype: int64

In [173]:
grades.Sam

Test1    94
Test2    77
Test3    90
Name: Sam, dtype: int64

In [179]:
grades.iloc[0]

Wally     87
Eva      100
Sam       94
Katie    100
Bob       83
Name: Test1, dtype: int64

In [182]:
grades.loc['Test1' : 'Test3']

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [184]:
grades.iloc[0:3]

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [187]:
grades.iloc[[0,2]]

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test3     70   90   90     82   85

In [189]:
grades.iloc[[1,2]]

Wally  Eva  Sam  Katie  Bob
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [190]:
grades.loc['Test1' : 'Test2', ['Eva' , 'Katie']]

Eva  Katie
Test1  100    100
Test2   87     81

In [192]:
grades.loc['Test2':'Test3' , ['Sam','Bob']]

Sam  Bob
Test2   77   65
Test3   90   85

In [194]:
grades.loc[['Test1' , 'Test3'] , ['Bob' , 'Wally']]

Bob  Wally
Test1   83     87
Test3   85     70

In [195]:
grades.iloc[[0,2] , 0:3]

Wally  Eva  Sam
Test1     87  100   94
Test3     70   90   90

In [196]:
grades[grades>=90]

Wally    Eva   Sam  Katie  Bob
Test1    NaN  100.0  94.0  100.0  NaN
Test2   96.0    NaN   NaN    NaN  NaN
Test3    NaN   90.0  90.0    NaN  NaN

In [197]:
grades [(grades >= 80) & (grades < 90)]

Wally   Eva  Sam  Katie   Bob
Test1   87.0   NaN  NaN    NaN  83.0
Test2    NaN  87.0  NaN   81.0   NaN
Test3    NaN   NaN  NaN   82.0  85.0

In [199]:
grades [(grades > 50) & (grades <80)]

Wally  Eva   Sam  Katie   Bob
Test1    NaN  NaN   NaN    NaN   NaN
Test2    NaN  NaN  77.0    NaN  65.0
Test3   70.0  NaN   NaN    NaN   NaN

In [200]:
grades.at ['Test2' , 'Eva']

87

In [201]:
grades.iat[2,0]

70

In [202]:
grades.at['Test2' , 'Eva'] = 100


In [205]:
grades.at['Test2' , 'Eva']

100

In [206]:
grades.iat[1,2] = 87

In [207]:
grades.iat[1,2]

87

In [208]:
foods_dict = {'Mohamed' : ['Ta3mya','Fool','Tagen'],
              'Marina' : ['SeeFood' , 'Egg' , 'Cola'],
              'Dina' : ['Kabab' , 'Kofta','Koshary']
              }


In [209]:
foods = pd.DataFrame(foods_dict)

In [210]:
foods

Mohamed   Marina     Dina
0  Ta3mya  SeeFood    Kabab
1    Fool      Egg    Kofta
2   Tagen     Cola  Koshary

In [214]:
foods.iloc[[1],1:3]

Marina   Dina
1    Egg  Kofta

In [216]:
grades.describe()

Wally         Eva        Sam       Katie        Bob
count   3.000000    3.000000   3.000000    3.000000   3.000000
mean   84.333333   96.666667  90.333333   87.666667  77.666667
std    13.203535    5.773503   3.511885   10.692677  11.015141
min    70.000000   90.000000  87.000000   81.000000  65.000000
25%    78.500000   95.000000  88.500000   81.500000  74.000000
50%    87.000000  100.000000  90.000000   82.000000  83.000000
75%    91.500000  100.000000  92.000000   91.000000  84.000000
max    96.000000  100.000000  94.000000  100.000000  85.000000

In [227]:
pd.set_option('display.precision', 3)

In [228]:
grades.describe()

Wally      Eva     Sam    Katie     Bob
count   3.000    3.000   3.000    3.000   3.000
mean   84.333   96.667  90.333   87.667  77.667
std    13.204    5.774   3.512   10.693  11.015
min    70.000   90.000  87.000   81.000  65.000
25%    78.500   95.000  88.500   81.500  74.000
50%    87.000  100.000  90.000   82.000  83.000
75%    91.500  100.000  92.000   91.000  84.000
max    96.000  100.000  94.000  100.000  85.000

In [229]:
grades.mean()

Wally    84.333
Eva      96.667
Sam      90.333
Katie    87.667
Bob      77.667
dtype: float64

In [230]:
grades.T

Test1  Test2  Test3
Wally     87     96     70
Eva      100    100     90
Sam       94     87     90
Katie    100     81     82
Bob       83     65     85

In [232]:
grades.T.describe()

Test1    Test2   Test3
count    5.000    5.000   5.000
mean    92.800   85.800  83.400
std      7.662   13.809   8.234
min     83.000   65.000  70.000
25%     87.000   81.000  82.000
50%     94.000   87.000  85.000
75%    100.000   96.000  90.000
max    100.000  100.000  90.000

In [233]:
grades.T.mean()

Test1    92.8
Test2    85.8
Test3    83.4
dtype: float64

In [234]:
grades.sort_index(ascending = False)

Wally  Eva  Sam  Katie  Bob
Test3     70   90   90     82   85
Test2     96  100   87     81   65
Test1     87  100   94    100   83

In [238]:
grades.sort_values(by='Test1' , axis=1,ascending=False)

Eva  Katie  Sam  Wally  Bob
Test1  100    100   94     87   83
Test2  100     81   87     96   65
Test3   90     82   90     70   85

In [246]:
grades.T.sort_values(by = 'Test1' , ascending=False)

Test1  Test2  Test3
Eva      100    100     90
Katie    100     81     82
Sam       94     87     90
Wally     87     96     70
Bob       83     65     85

In [254]:
grades.loc['Test1'].sort_values(ascending=False , inplace= True)

In [257]:
grades.loc['Test1'].sort_values(by='Test1', ascending=False, inplace=True)

TypeError: Series.sort_values() got an unexpected keyword argument 'by'