### Exercises

In [1]:
import numpy as np

### 7.1

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.full((2,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [14]:
np.full((3,4),8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

### 7.2

In [44]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [45]:
a ** 3

array([[ 0,  1],
       [ 8, 27]], dtype=int32)

In [46]:
a + 7

array([[ 7,  8],
       [ 9, 10]])

In [47]:
a * 2

array([[0, 2],
       [4, 6]])

In [41]:
for i in a:
    i **= 3


In [42]:
a

array([[ 0,  1],
       [ 8, 27]])

### 7.3

(Element-Wise array Multiplication) Create a 10-by-10 array containing the
number 4 in each position. Create a second 10-by-10 array containing the numbers 1 to
100 in ascending order. Multiply the first array by the second array.

In [48]:
ar = np.full((10,10),4)
ar

array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [51]:
ar2 = np.arange(1,101).reshape(10,10)
ar2

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [52]:
ar * ar2

array([[  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [ 44,  48,  52,  56,  60,  64,  68,  72,  76,  80],
       [ 84,  88,  92,  96, 100, 104, 108, 112, 116, 120],
       [124, 128, 132, 136, 140, 144, 148, 152, 156, 160],
       [164, 168, 172, 176, 180, 184, 188, 192, 196, 200],
       [204, 208, 212, 216, 220, 224, 228, 232, 236, 240],
       [244, 248, 252, 256, 260, 264, 268, 272, 276, 280],
       [284, 288, 292, 296, 300, 304, 308, 312, 316, 320],
       [324, 328, 332, 336, 340, 344, 348, 352, 356, 360],
       [364, 368, 372, 376, 380, 384, 388, 392, 396, 400]])

### 7.4

In [83]:
np.array([[range(10,-1,-2)] ,[range(0,11,2)]] )

array([[[10,  8,  6,  4,  2,  0]],

       [[ 0,  2,  4,  6,  8, 10]]])

### 7.5

In [90]:
array = np.array([[range(10,-1,-2)] ,[range(0,11,2)]] )

In [91]:
flattened = np.array([[range(10,-1,-2)] ,[range(0,11,2)]] ).flatten()

In [85]:
flattened

array([10,  8,  6,  4,  2,  0,  0,  2,  4,  6,  8, 10])

In [86]:
flattened[1] = 10

In [87]:
flattened

array([10, 10,  6,  4,  2,  0,  0,  2,  4,  6,  8, 10])

In [88]:
np.array([[range(10,-1,-2)] ,[range(0,11,2)]] ).flatten()

array([10,  8,  6,  4,  2,  0,  0,  2,  4,  6,  8, 10])

In [92]:
raveled = np.array([[range(10,-1,-2)] ,[range(0,11,2)]] ).ravel()
raveled

array([10,  8,  6,  4,  2,  0,  0,  2,  4,  6,  8, 10])

In [97]:
np.array([range(10,-1,-2) ,range(0,11,2)] )

array([[10,  8,  6,  4,  2,  0],
       [ 0,  2,  4,  6,  8, 10]])

In [95]:
print("Comparison after using ravel:", np.array_equal(flattened, raveled))
                

Comparison after using ravel: True


### 7.6

In [113]:
a = np.linspace(1.1,6.6,6)
a

array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6])

In [114]:
a.astype('i')

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [115]:
a.astype('f')

array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6], dtype=float32)

In [117]:
a.astype('str')

array(['1.1', '2.2', '3.3000000000000003', '4.4', '5.5', '6.6'],
      dtype='<U32')

### 7.9

In [123]:
array = np.arange(1,16).reshape(3,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [124]:
array[2]

array([11, 12, 13, 14, 15])

In [133]:
array[:,4]

array([ 5, 10, 15])

In [138]:
array[:,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [139]:
array[1,4]

10

In [147]:
array[[1,2] ]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [171]:
array[1:3 ,[0,2,4]]

array([[ 6,  8, 10],
       [11, 13, 15]])

### 7.14

In [181]:
array1 = np.array([[0,2] , [4,6]])
array2 = np.array([[1,3] , [5,7]])
array1

array([[0, 2],
       [4, 6]])

In [195]:
array3 = np.hstack((array1,array2))

In [196]:
print(array3)

[[0 2 1 3]
 [4 6 5 7]]


In [197]:
array3[0]

array([0, 2, 1, 3])

In [198]:
array4 = array3[0]
array5 = array3[1]

In [212]:
array4 , array5 = np.vsplit(array3,2)


In [213]:
array4

array([[0, 1, 2, 3]])

In [205]:
array5

array([[4, 6, 5, 7]])

In [216]:
array4.sort()
array5.sort()

In [217]:
array5

array([[4, 5, 6, 7]])

In [215]:
array4

array([[0, 1, 2, 3]])

In [221]:
array6 = np.hstack((array4,array5))
array6

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [224]:
array7 = np.vstack((array6 , array6 *10))

In [225]:
array7

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 0, 10, 20, 30, 40, 50, 60, 70]])

In [235]:
concatarray = np.concatenate((array1,array2),axis=1)

In [238]:
np.sort(concatarray)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [241]:
arr = np.zeros(4).astype('i')

In [244]:
arr = np.tile(arr,2)

In [245]:
arr = np.vstack(arr)

In [247]:
arr = np.hstack(arr)

In [248]:
arr

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [249]:
square_0 = np.zeros((2, 2))

In [250]:
square_1 = np.ones((2, 2))

In [253]:
row_1 = np.tile(np.hstack((square_0, square_1)), (1, 4))
row_1

array([[0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1.],
       [0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1.]])

In [254]:
row_2 = np.tile(np.hstack((square_1, square_0)), (1, 4))

In [255]:
row_2

array([[1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0.],
       [1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0.]])

In [264]:
arraytest = np.array([1,2,3,4])

np.tile(arraytest,(1,4))
row1 =np.tile(np.hstack((arraytest)) , (1,4))
row2 =np.tile(np.hstack((arraytest)) , (1,4))

In [269]:
cehck = np.tile(np.vstack((row1,row2)) , (4,1))
cehck

array([[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]])

In [270]:
import numpy as np

# Define a "square" as a 2x2 array of ones or zeros
square_0 = np.zeros((2, 2))
square_1 = np.ones((2, 2))

# Create one row of the checkerboard pattern
row_1 = np.tile(np.hstack((square_0, square_1)), (1, 4))
row_2 = np.tile(np.hstack((square_1, square_0)), (1, 4))

# Repeat the row to create the checkerboard pattern
checkerboard = np.tile(np.vstack((row_1, row_2)), (4, 1))

print(checkerboard)

[[0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1.]
 [0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0.]
 [1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1.]
 [0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0.]
 [1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1.]
 [0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0.]
 [1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1.]
 [0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0.]
 [1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0.]]


In [276]:
arr = np.array([4, 4, 2, 1, 6, 8, 3, 3, 4, 15, 23])

In [277]:
freq_bin = np.bincount(arr)

In [278]:
freq_bin

array([0, 1, 1, 2, 3, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1], dtype=int64)

In [279]:
votes = np.random.randint(2, size=99)

In [284]:
votes

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1])

In [286]:
vote_counts = np.bincount(votes)
vote_counts

array([46, 53], dtype=int64)

In [283]:
print("Votes for Candidate 1: ", vote_counts[0])
print("Votes for Candidate 2: ", vote_counts[1])

Votes for Candidate 1:  46
Votes for Candidate 2:  53


### 7.20

In [306]:
%timeit rolls_array = np.random.randint(1,2,10000)

9.3 µs ± 379 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [307]:
%timeit rolls = np.random.randint(1,2,1000000)

1.79 ms ± 33.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [308]:
import random

%timeit rolls_list = \
    [random.randrange(1,2) for i in range(0,1000000)]

435 ms ± 9.58 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### 7.21

In [328]:
import copy
dict = {'Sophia' : [97,88]}

In [325]:
dict2 = dict.copy()

In [326]:
dict2

{'Sophia': [97, 88]}

In [329]:
dict3 = copy.deepcopy(dict)

In [331]:
dict3[0] = 'Hello' 

In [332]:
dict

{'Sophia': [97, 88]}

In [333]:
dict3

{'Sophia': [97, 88], 0: 'Hello'}

In [334]:
dict2

{'Sophia': [97, 88]}

In [335]:
dict2[0] = "Mohamed"


In [336]:
dict2

{'Sophia': [97, 88], 0: 'Mohamed'}

In [337]:
dict

{'Sophia': [97, 88]}